options ls=78;
title "Confidence Intervals - Milk Truck Cost";
%let p=3;
data milk;
  infile "x:\505\hw5_milk.dat";
  input fuelCost repairCost capitalCost truckType $;
  run;
data gasoline;
  set milk;
  if truckType="gasoline";
  variable="fuelCost";   x=fuelCost; output;
  variable="repairCost";     x=repairCost;   output;
  variable="capitalCost";    x=capitalCost;  output;
  keep truckType variable x;
  run;
proc sort;
  by variable;
  run;
proc means noprint;
  by variable;
  id truckType;
  var x;
  output out=pop1 n=n1 mean=xbar1 var=s21;

data diesel;
  set milk;
  if truckType="diesel";
  variable="fuelCost";   x=fuelCost; output;
  variable="repairCost";     x=repairCost;   output;
  variable="capitalCost";    x=capitalCost;  output;
  keep truckType variable x;
  run;
proc sort;
  by variable;
  run;
proc means noprint;
  by variable;
  id truckType;
  var x;
  output out=pop2 n=n2 mean=xbar2 var=s22;
data combine;
  merge pop1 pop2;
  by variable;
  f=finv(0.99,&p,n1+n2-&p-1);
  t=tinv(1-0.005/&p,n1+n2-2);
  sp=((n1-1)*s21+(n2-1)*s22)/(n1+n2-2);
  losim=xbar1-xbar2-sqrt(&p*(n1+n2-2)*f*(1/n1+1/n2)*sp/(n1+n2-&p-1));
  upsim=xbar1-xbar2+sqrt(&p*(n1+n2-2)*f*(1/n1+1/n2)*sp/(n1+n2-&p-1));
  lobon=xbar1-xbar2-t*sqrt((1/n1+1/n2)*sp);
  upbon=xbar1-xbar2+t*sqrt((1/n1+1/n2)*sp);
  run;
proc print;
  run;