options ls=78;
title "Paired Hotelling's T-Square";
data mineral;
  infile "x:\505\hw5_mineral.dat";
  input dradius radius dhumerus humerus dulna ulna;
  variable=1; diff=dradius - radius; output;
  variable=2; diff=dhumerus - humerus; output;
  variable=3; diff=dulna - ulna; output;
  drop dradius radius dhumerus humerus dulna ulna;
  run;

proc sort;
  by variable;
  run;
proc means noprint;
  by variable;
  var diff;
  output out=a n=n mean=xbar var=s2;
  run;
data b;
  set a;
  f=finv(0.95,&p,n-&p);
  t=tinv(1-0.025/&p,n-1);
  losim=xbar-sqrt(&p*(n-1)*f*s2/(n-&p)/n); 
  upsim=xbar+sqrt(&p*(n-1)*f*s2/(n-&p)/n); 
  lobon=xbar-t*sqrt(s2/n);
  upbon=xbar+t*sqrt(s2/n);
  run;
proc print;
  run;