options ls=78;
title "Profile Plot - Swiss Notes";
%let p=6;
data swiss;
  infile "x:\505\hw5_swiss.dat";
  input length leftWidth rightWidth bottomMargin topMargin diagonal;
  variable="length"; ratio=length/215; output;
  variable="leftWidth";    ratio=leftWidth/130;    output;
  variable="rightWidth"; ratio=rightWidth/130; output;
  variable="bottomMargin";   ratio=bottomMargin/9;       output;
  variable="topMargin";   ratio=topMargin/10;       output;
  variable="diagonal";   ratio=diagonal/141.354;       output;
  keep variable ratio;
  run;
proc sort;
  by variable;
  run;
proc means;
  by variable;
  var ratio;
  output out=a n=n mean=xbar var=s2;
  run;
data b;
  set a;
  f=finv(0.95,&p,n-&p);
  ratio=xbar; output;
  ratio=xbar-sqrt(&p*(n-1)*f*s2/(n-&p)/n); output;
  ratio=xbar+sqrt(&p*(n-1)*f*s2/(n-&p)/n); output;
  run;
proc gplot;
  axis1 length=4 in;
  axis2 length=6 in;
  plot ratio*variable / vaxis=axis1 haxis=axis2 vref=1 lvref=21;
  symbol v=none i=hilot color=black;
  run;