options ls=78;
title "Hotellings T2 - Swiss Notes";
data swiss;
  infile "x:\505\hw5_swiss.dat";
  input length leftWidth rightWidth bottomMargin topMargin diagonal;
  run;
proc iml;
  start hotel;
    mu0={215, 130, 130, 9, 10, 141.354};
    one=j(nrow(x),1,1);
    ident=i(nrow(x));
    ybar=x`*one/nrow(x);
    s=x`*(ident-one*one`/nrow(x))*x/(nrow(x)-1.0);
    print mu0 ybar;
    print s;
    t2=nrow(x)*(ybar-mu0)`*inv(s)*(ybar-mu0);
    f=(nrow(x)-ncol(x))*t2/ncol(x)/(nrow(x)-1);
    df1=ncol(x);
    df2=nrow(x)-ncol(x);
    p=1-probf(f,df1,df2);
    print t2 f df1 df2 p;
  finish;
  use swiss;
  read all var{length leftWidth rightWidth bottomMargin topMargin diagonal} into x;
  run hotel;
