options ls=78;
title "Profile Plot";
data pottery;
  infile "x:\505\hw6_skulls.dat";
  input X1 X2 X3 X4 period;
  measurement="X1"; amount=X1; output;
  measurement="X2"; amount=X2; output;
  measurement="X3"; amount=X3; output;
  measurement="X4"; amount=X4; output;
proc sort;
  by period measurement;
proc means;
  by period measurement;
  var amount;
  output out=a mean=mean;
proc gplot;
  axis1 length=3 in;
  axis2 length=4.5 in;
  plot mean*measurement=period / vaxis=axis1 haxis=axis2;
  symbol1 v=J f=special h=2 l=1 i=join color=black;
  symbol2 v=K f=special h=2 l=1 i=join color=black;
  symbol3 v=L f=special h=2 l=1 i=join color=black;
run;
