options ls=78;
title "Profile Plot - Drugs Data";
data dogs;
  infile "x:\505\hw7_drugs.dat";
  input person h1 h2 h3 h4 treat $;
  time=5;  k=h1; output;
  time=10;  k=h2; output;
  time=15;  k=h3; output;
  time=20; k=h4; output;
  drop h1 h2 h3 h4;
  run;
proc sort;
  by treat time;
  run;
proc means;
  by treat time;
  var k;
  output out=a mean=mean;
filename t1 "drugs.ps";
goptions device=ps300 gsfname=t1 gsfmode=replace;
proc gplot;
  axis1 length=4 in;
  axis2 length=6 in;
  plot mean*time=treat / vaxis=axis1 haxis=axis2;
  symbol1 v=J f=special h=2 i=join color=black;
  symbol2 v=K f=special h=2 i=join color=black;
  symbol3 v=L f=special h=2 i=join color=black;
  symbol4 v=M f=special h=2 i=join color=black;
  run;
  