options ls=78;
title "Profile Plot - Drugs Data";
data dogs;
  infile "x:\505\hw7_drugs.dat";
  input person h1 h2 h3 h4 treat $;
  time=5;  k=h1; output;
  time=10;  k=h2; output;
  time=15;  k=h3; output;
  time=20; k=h4; output;
  drop h1 h2 h3 h4;
  run;
proc glm;
  class treat person time;
  model k=treat person(treat) time treat*time;
  test h=treat e=person(treat);
  run; 